name: Conformance
on:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  conformance:
    name: Conformance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test conformance
        run: make conformance
      - name: Test protokt conformance
        run: ./gradlew conformance:conformance -Pconformance-protokt
      - name: Test protokt dynamic message conformance
        run: ./gradlew conformance:conformance -Pconformance-protokt-dynamic
